### PR TITLE
Switch back to setuptools

### PR DESCRIPTION
**Pull request by href**
See #2

### CODE REVIEW

**Comment by phlax** [comment]
@href if i add you to repo and pypi - are you happy to release? if not im happy to do it

**Comment by href** [comment]
Sure, I'd be happy to help you out. I use scrambler in a few projects already, so I'm interested in keeping the lights on :)

I'm `href` on PyPI as well.

**Comment by href** [comment]
Cheers! I'll merge and release 0.0.5

**Comment by phlax** [comment]
great thanks @href - pypi creds should be there - im happy to review any PRs

**Comment by href** [comment]
Alright, I'll be sure to send them your way if I encounter anything. To be honest though, apart from this I've had no issues whatsoever :)

**Pull request merged**
